name: Build and Deploy to GitHub Packages

on:
  push:
    branches:
      - main # or the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # Use 'adopt' or other distributions if you prefer

      - name: Build with Maven
        run: mvn clean install

      - name: Install AWS SAM CLI
        run: |
          curl -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli.zip
          unzip aws-sam-cli.zip -d sam-installation
          sudo ./sam-installation/install --update
          sam --version

      - name: Run SAM build
        run: sam build

      - name: Publish to GitHub Packages
        run: |
          PACKAGE_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn -B deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
